<?php
return array (
  'autogenerated-1-c4ca4238a0b923820dcc509a6f75849b' => 
  array (
    'base' => 'https://v12.4.ddev.site/autogenerated-1',
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 1,
    'routes' => 
    array (
    ),
  ),
);
#